function adminID = importfileAdmin(filepath, folderpath)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   ADMINID = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   ADMINID = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   adminID = importfile('old_zCumNDVI_eMODIS_extendedBy_GIMMS.csv',3,
%   122);
%
%    See also TEXTSCAN.
filesavg = dir(strcat(filepath,folderpath));
fileIndexavg = find(~[filesavg.isdir]);
nfilesavg = length(fileIndexavg);
% filesmax = dir(strcat(filepath,'Maxz_base1981S-2012S\'));
% fileIndexmax = find(~[filesmax.isdir]);
% nfilesmax = length(fileIndexmax);

for i=1:1%nfilesavg
        fileNameavg{i}= filesavg(fileIndexavg(i)).name;
        filename = strcat(filepath,folderpath,fileNameavg{i});
end        





% Auto-generated by MATLAB on 2014/07/09 18:34:54

%% Initialize variables.


delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
adminID = dataArray{:, 1};

