<?php
/**
 * @file
 * Code for the IBLI General feature.
 */

include_once 'ibli_general.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Contact form modifications.
 */
function ibli_general_form_contact_site_form_alter(&$form, &$form_state) {
  // Add placeholders.
  $form['name']['#attributes'] = array(
    'placeholder' => t('Enter name'),
  );

  $form['mail']['#attributes'] = array(
    'placeholder' => t('Enter e-mail'),
  );

  $form['subject']['#attributes'] = array(
    'placeholder' => t('Enter subject'),
  );

  $form['message']['#attributes'] = array(
    'placeholder' => t('Enter message'),
  );

  // Remove default values.
  unset($form['mail']['#default_value']);
  unset($form['name']['#default_value']);

  // Do not allow sending a copy.
  $form['copy']['#access'] = FALSE;

  // Make button green.
  $form['actions']['submit']['#attributes'] = array(
    'class' => array('btn-green'),
  );
}

/**
 * Implements hook_form_alter().
 */
function ibli_general_form_alter(&$form, &$form_state, $form_id)
{
  if(preg_match('/webform_client_form/i', $form_id))
  {
    $form['#validate'][]='ibli_general_form_validate';
    return $form;
  }
}

/**
 * Custom validation to Email/phone submission.
 */
function ibli_general_form_validate($form, &$form_state) {
  $field_value = $form_state['values']['submitted']['email_phone'];
  // Checking if the submitted value is an International phone number.
  if(preg_match('[^\+[0-9]]', trim($field_value))) {
    // Then we let the form pass and don't do anything.
    return TRUE;
  }
  // Checking if the submitted value is an email address.
  elseif (valid_email_address($field_value)) {
    // Then we have to send an email to the user.
    //webform_submission_send_mail();
    return TRUE;
  }
  else {
    form_set_error('email_phone', t('Email address is invalid/ Phone number should contain country code.(+000)'));
  }
}
