<?php
/**
 * @file
 * Code for the IBLI News feature.
 */

include_once 'ibli_news.features.inc';


function ibli_news_get_news() {

  $query= new EntityFieldQuery();

  // Get all the news
  $result = $query->entityCondition('entity_type', 'node')
                  ->entityCondition('bundle', 'news')
                  ->propertyCondition('status', NODE_PUBLISHED)
                  ->execute();

  if(!isset($result['node'])) {
    return;
  }

  // Get news IDs.
  $news = array_keys($result['node']);
  $news_nodes = node_load_multiple($news);

  $html = NULL;
  foreach ($news_nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);

    $description = $wrapper->body->value->value();
    if (strlen($description) >= 100) {
      $description =  substr($description, 0, 100) . "...";
    }

    $news_items[] = array(
      'link' => $wrapper->field_link->value(),
      'title' => $wrapper->label(),
      'date' => date('D, d M Y G:i:s P', $wrapper->field_publish_date->value()),
      'description' => $description,
    );
    $html .= theme('ibli_news', array('news_items' => $news_items));
  }
  return $html;
}

/**
 * Delegated hook_theme().
 */
function ibli_news_theme() {
  return array(
    'ibli_news' =>   array(
      'variables' => array(
        'news_items' => NULL,
      ),
      'path' => drupal_get_path('module', 'ibli_news') .'/templates',
      'template' => 'ibli-news',
    ),
  );
}
